
#thymeleaf:
#  prefix=classpath: templates/
#  suffix: .html
#  check-template-location: true
#  cache: false
#  mvc:
#    static-path-pattern: "/static/**"


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          naver:     #oauth 등록
            client-id: n8_VwuqF5jQFAvbnsIMa
            client-secret: 33ZQh00Fj6
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
